// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReturnResultCode int32

const (
	ReturnResultCode_CODE_SUCCESS ReturnResultCode = 0
	// Params error start--------------------------------
	// Params validate error
	ReturnResultCode_CODE_PARAMS_ERROR ReturnResultCode = 100
	// Check sign error
	ReturnResultCode_CODE_CHECK_SIGN_ERROR ReturnResultCode = 101
	// --------------------------------
	ReturnResultCode_CODE_SYSTEM_ERROR ReturnResultCode = 999
)

var ReturnResultCode_name = map[int32]string{
	0:   "CODE_SUCCESS",
	100: "CODE_PARAMS_ERROR",
	101: "CODE_CHECK_SIGN_ERROR",
	999: "CODE_SYSTEM_ERROR",
}

var ReturnResultCode_value = map[string]int32{
	"CODE_SUCCESS":          0,
	"CODE_PARAMS_ERROR":     100,
	"CODE_CHECK_SIGN_ERROR": 101,
	"CODE_SYSTEM_ERROR":     999,
}

func (x ReturnResultCode) String() string {
	return proto.EnumName(ReturnResultCode_name, int32(x))
}

func (ReturnResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

// 付款状态类型
type PayType int32

const (
	// 直接付款
	PayType_PAY PayType = 0
	// 签约付款
	PayType_SIGN_PAY PayType = 1
	// 退款
	PayType_REFUND PayType = 2
	// 取消签约
	PayType_UNSIGN PayType = 3
	// 向用户转账
	PayType_TRANSFER PayType = 4
)

var PayType_name = map[int32]string{
	0: "PAY",
	1: "SIGN_PAY",
	2: "REFUND",
	3: "UNSIGN",
	4: "TRANSFER",
}

var PayType_value = map[string]int32{
	"PAY":      0,
	"SIGN_PAY": 1,
	"REFUND":   2,
	"UNSIGN":   3,
	"TRANSFER": 4,
}

func (x PayType) String() string {
	return proto.EnumName(PayType_name, int32(x))
}

func (PayType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type PayStatus int32

const (
	// 成功
	PayStatus_SUCCESS PayStatus = 0
	// 处理中
	PayStatus_DEALING PayStatus = 1
	// 失败
	PayStatus_FAIL PayStatus = 2
)

var PayStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "DEALING",
	2: "FAIL",
}

var PayStatus_value = map[string]int32{
	"SUCCESS": 0,
	"DEALING": 1,
	"FAIL":    2,
}

func (x PayStatus) String() string {
	return proto.EnumName(PayStatus_name, int32(x))
}

func (PayStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

type Method int32

const (
	// 银联
	Method_WEB Method = 0
	// 手机wap支付
	Method_WAP Method = 1
	// 原生扫码支付
	Method_APP Method = 2
	// SDK支付
	Method_SDK Method = 3
	// 二维码支付
	// 跟APP的区别在于，改支付方式直接返回二维码，而APP则可能返回url响应，需要商户根据url生成二维码
	Method_QR_CODE Method = 5
	// 用于后台转账
	Method_SERVER Method = 4
)

var Method_name = map[int32]string{
	0: "WEB",
	1: "WAP",
	2: "APP",
	3: "SDK",
	5: "QR_CODE",
	4: "SERVER",
}

var Method_value = map[string]int32{
	"WEB":     0,
	"WAP":     1,
	"APP":     2,
	"SDK":     3,
	"QR_CODE": 5,
	"SERVER":  4,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}

func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

type ReturnResult struct {
	Code                 ReturnResultCode `protobuf:"varint,1,opt,name=code,proto3,enum=pay.ReturnResultCode" json:"code,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Describe             string           `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReturnResult) Reset()         { *m = ReturnResult{} }
func (m *ReturnResult) String() string { return proto.CompactTextString(m) }
func (*ReturnResult) ProtoMessage()    {}
func (*ReturnResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *ReturnResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnResult.Unmarshal(m, b)
}
func (m *ReturnResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnResult.Marshal(b, m, deterministic)
}
func (m *ReturnResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnResult.Merge(m, src)
}
func (m *ReturnResult) XXX_Size() int {
	return xxx_messageInfo_ReturnResult.Size(m)
}
func (m *ReturnResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnResult proto.InternalMessageInfo

func (m *ReturnResult) GetCode() ReturnResultCode {
	if m != nil {
		return m.Code
	}
	return ReturnResultCode_CODE_SUCCESS
}

func (m *ReturnResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReturnResult) GetDescribe() string {
	if m != nil {
		return m.Describe
	}
	return ""
}

type Product struct {
	// 产品ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 产品名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 描述
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("pay.ReturnResultCode", ReturnResultCode_name, ReturnResultCode_value)
	proto.RegisterEnum("pay.PayType", PayType_name, PayType_value)
	proto.RegisterEnum("pay.PayStatus", PayStatus_name, PayStatus_value)
	proto.RegisterEnum("pay.Method", Method_name, Method_value)
	proto.RegisterType((*ReturnResult)(nil), "pay.ReturnResult")
	proto.RegisterType((*Product)(nil), "pay.Product")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xc5, 0x36, 0xc5, 0x30, 0xa0, 0x68, 0x3a, 0x12, 0x15, 0xcd, 0x09, 0xe5, 0x94, 0x72, 0x30,
	0x52, 0xfb, 0x0b, 0x1c, 0xb3, 0xa4, 0x28, 0xc1, 0xb8, 0xbb, 0xd0, 0x2a, 0x27, 0x64, 0xec, 0x2d,
	0xa1, 0x02, 0xaf, 0xe5, 0x8f, 0x83, 0x7f, 0x71, 0xff, 0x46, 0xb5, 0x1b, 0x68, 0x51, 0x6f, 0x6f,
	0xde, 0xbc, 0x79, 0xef, 0xad, 0xb4, 0x30, 0x48, 0xd4, 0xe9, 0xa4, 0x32, 0x2f, 0x2f, 0x54, 0xa5,
	0xc8, 0xc9, 0xe3, 0xe6, 0x76, 0xbc, 0x57, 0x6a, 0x7f, 0x94, 0x53, 0x43, 0xed, 0xea, 0x9f, 0xd3,
	0x54, 0x96, 0x49, 0x71, 0xc8, 0x2b, 0x55, 0xbc, 0xc9, 0xee, 0x14, 0x0c, 0xb8, 0xac, 0xea, 0x22,
	0xe3, 0xb2, 0xac, 0x8f, 0x15, 0x7d, 0x82, 0x76, 0xa2, 0x52, 0x39, 0xb2, 0xc6, 0xd6, 0xfd, 0xcd,
	0xe7, 0xa1, 0x97, 0xc7, 0x8d, 0x77, 0x2d, 0x08, 0x54, 0x2a, 0xb9, 0x91, 0xd0, 0x08, 0xdc, 0x93,
	0x2c, 0xcb, 0x78, 0x2f, 0x47, 0xf6, 0xd8, 0xba, 0xef, 0xf1, 0xcb, 0x48, 0xb7, 0xd0, 0x7d, 0x0b,
	0xda, 0xc9, 0x91, 0x63, 0x56, 0x7f, 0xe7, 0xbb, 0x15, 0xb8, 0x51, 0xa1, 0xd2, 0x3a, 0xa9, 0xe8,
	0x06, 0xec, 0x43, 0x6a, 0x92, 0x7a, 0xdc, 0x3e, 0xa4, 0x44, 0xd0, 0xce, 0xe2, 0xd3, 0xc5, 0xcd,
	0x60, 0x1a, 0x43, 0xff, 0xd2, 0xf9, 0xa0, 0xb2, 0xb3, 0xdb, 0x35, 0x35, 0xc9, 0x00, 0xff, 0x2f,
	0x48, 0x08, 0x83, 0x60, 0x35, 0x63, 0x5b, 0xb1, 0x09, 0x02, 0x26, 0x04, 0xb6, 0x68, 0x08, 0xef,
	0x0d, 0x13, 0xf9, 0xdc, 0x5f, 0x8a, 0x2d, 0xe3, 0x7c, 0xc5, 0x31, 0xa5, 0x8f, 0x30, 0x34, 0x74,
	0xf0, 0x95, 0x05, 0x4f, 0x5b, 0xb1, 0x78, 0x0c, 0xcf, 0x2b, 0x49, 0x1f, 0xce, 0x17, 0xe2, 0x45,
	0xac, 0xd9, 0xf2, 0x4c, 0xff, 0x76, 0x27, 0x73, 0x70, 0xa3, 0xb8, 0x59, 0x37, 0xb9, 0x24, 0x17,
	0x9c, 0xc8, 0x7f, 0xc1, 0x16, 0x0d, 0xa0, 0x6b, 0x6e, 0xf5, 0x64, 0x11, 0x40, 0x87, 0xb3, 0xf9,
	0x26, 0x9c, 0xa1, 0xad, 0xf1, 0x26, 0xd4, 0x3b, 0x74, 0xb4, 0x6a, 0xcd, 0xfd, 0x50, 0xcc, 0x19,
	0xc7, 0xf6, 0x64, 0x0a, 0xbd, 0x28, 0x6e, 0x44, 0x15, 0x57, 0x75, 0x49, 0x7d, 0x70, 0xff, 0x75,
	0xed, 0x83, 0x3b, 0x63, 0xfe, 0xf3, 0x22, 0x7c, 0x44, 0x8b, 0xba, 0xd0, 0x9e, 0xfb, 0x8b, 0x67,
	0xb4, 0x27, 0x0c, 0x3a, 0x4b, 0x59, 0xbd, 0xaa, 0x54, 0xe7, 0xfe, 0x60, 0x0f, 0xd8, 0x32, 0xc0,
	0x8f, 0xd0, 0xd2, 0xc0, 0x8f, 0x22, 0xb4, 0x35, 0x10, 0xb3, 0x27, 0x74, 0xb4, 0xc9, 0x37, 0xbe,
	0xd5, 0x2f, 0xc0, 0x77, 0xba, 0x85, 0x60, 0xfc, 0xbb, 0xce, 0x7d, 0x20, 0xc0, 0xbc, 0xde, 0x79,
	0xf9, 0x2f, 0x95, 0x78, 0xc9, 0x6b, 0x9c, 0x65, 0xf2, 0xb8, 0xeb, 0x98, 0xcf, 0xf0, 0xe5, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xe5, 0xe8, 0x7e, 0x43, 0x02, 0x00, 0x00,
}
