// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: notify.proto

package pay

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _notify_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on HttpNotifyRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *HttpNotifyRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Channel

	// no validation rules for Account

	// no validation rules for OrderId

	// no validation rules for HttpMethod

	if v, ok := interface{}(m.GetBody()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HttpNotifyRequestValidationError{
				field:  "Body",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// HttpNotifyRequestValidationError is the validation error returned by
// HttpNotifyRequest.Validate if the designated constraints aren't met.
type HttpNotifyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpNotifyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpNotifyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpNotifyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpNotifyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpNotifyRequestValidationError) ErrorName() string {
	return "HttpNotifyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HttpNotifyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpNotifyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpNotifyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpNotifyRequestValidationError{}

// Validate checks the field values on HttpNotifyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *HttpNotifyResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Body

	// no validation rules for Header

	return nil
}

// HttpNotifyResponseValidationError is the validation error returned by
// HttpNotifyResponse.Validate if the designated constraints aren't met.
type HttpNotifyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpNotifyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpNotifyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpNotifyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpNotifyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpNotifyResponseValidationError) ErrorName() string {
	return "HttpNotifyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HttpNotifyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpNotifyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpNotifyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpNotifyResponseValidationError{}
