// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notify.proto

package pay

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpNotifyRequest struct {
	Channel              string             `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Account              string             `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	OrderId              string             `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	HttpMethod           string             `protobuf:"bytes,4,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	Body                 *httpbody.HttpBody `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *HttpNotifyRequest) Reset()         { *m = HttpNotifyRequest{} }
func (m *HttpNotifyRequest) String() string { return proto.CompactTextString(m) }
func (*HttpNotifyRequest) ProtoMessage()    {}
func (*HttpNotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{0}
}

func (m *HttpNotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpNotifyRequest.Unmarshal(m, b)
}
func (m *HttpNotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpNotifyRequest.Marshal(b, m, deterministic)
}
func (m *HttpNotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpNotifyRequest.Merge(m, src)
}
func (m *HttpNotifyRequest) XXX_Size() int {
	return xxx_messageInfo_HttpNotifyRequest.Size(m)
}
func (m *HttpNotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpNotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HttpNotifyRequest proto.InternalMessageInfo

func (m *HttpNotifyRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *HttpNotifyRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *HttpNotifyRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *HttpNotifyRequest) GetHttpMethod() string {
	if m != nil {
		return m.HttpMethod
	}
	return ""
}

func (m *HttpNotifyRequest) GetBody() *httpbody.HttpBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type HttpNotifyResponse struct {
	Body                 []byte            `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Header               map[string]string `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HttpNotifyResponse) Reset()         { *m = HttpNotifyResponse{} }
func (m *HttpNotifyResponse) String() string { return proto.CompactTextString(m) }
func (*HttpNotifyResponse) ProtoMessage()    {}
func (*HttpNotifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{1}
}

func (m *HttpNotifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpNotifyResponse.Unmarshal(m, b)
}
func (m *HttpNotifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpNotifyResponse.Marshal(b, m, deterministic)
}
func (m *HttpNotifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpNotifyResponse.Merge(m, src)
}
func (m *HttpNotifyResponse) XXX_Size() int {
	return xxx_messageInfo_HttpNotifyResponse.Size(m)
}
func (m *HttpNotifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpNotifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HttpNotifyResponse proto.InternalMessageInfo

func (m *HttpNotifyResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *HttpNotifyResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpNotifyRequest)(nil), "pay.HttpNotifyRequest")
	proto.RegisterType((*HttpNotifyResponse)(nil), "pay.HttpNotifyResponse")
	proto.RegisterMapType((map[string]string)(nil), "pay.HttpNotifyResponse.HeaderEntry")
}

func init() { proto.RegisterFile("notify.proto", fileDescriptor_aba76cc4ebe272d4) }

var fileDescriptor_aba76cc4ebe272d4 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0x66, 0x92, 0x76, 0xb5, 0x6f, 0xf7, 0xa0, 0xc3, 0x52, 0xd2, 0xb5, 0xd0, 0x25, 0xf5, 0xb0,
	0xa7, 0x19, 0x5c, 0x41, 0xb4, 0x1e, 0xc4, 0x82, 0xb4, 0x1e, 0x14, 0xd9, 0xa3, 0x97, 0x32, 0x9b,
	0x4c, 0xbb, 0xd1, 0xcd, 0xbc, 0x31, 0x99, 0x14, 0xc2, 0xb2, 0x97, 0xfe, 0x00, 0x2f, 0xde, 0xc5,
	0x3f, 0xe0, 0x1f, 0xf1, 0x26, 0xfe, 0x05, 0x7f, 0x88, 0x64, 0xf2, 0x0a, 0x81, 0x2e, 0x82, 0xf6,
	0x36, 0xdf, 0xfb, 0xde, 0x37, 0xf3, 0xbd, 0xef, 0x25, 0x30, 0x30, 0xe8, 0xb2, 0xf3, 0x5a, 0xd8,
	0x02, 0x1d, 0xf2, 0xd0, 0xaa, 0x7a, 0xb4, 0x77, 0x81, 0x78, 0xb1, 0xd4, 0x52, 0xd9, 0x4c, 0x2e,
	0x9c, 0xb3, 0x73, 0x4c, 0x89, 0x1f, 0xed, 0x77, 0x28, 0x65, 0x0c, 0x3a, 0xe5, 0x32, 0x34, 0x25,
	0xb1, 0x07, 0xc4, 0x7a, 0x34, 0xaf, 0xce, 0xa5, 0xcb, 0x72, 0x5d, 0x3a, 0x95, 0x5b, 0x6a, 0x18,
	0x24, 0x98, 0xe7, 0x68, 0x5a, 0x14, 0x7f, 0x67, 0x70, 0xff, 0xd4, 0x39, 0xfb, 0xd6, 0x3b, 0x98,
	0xe9, 0x4f, 0x95, 0x2e, 0x1d, 0x8f, 0xe0, 0x4e, 0xb2, 0x50, 0xc6, 0xe8, 0x65, 0xc4, 0xc6, 0x6c,
	0xb2, 0x33, 0xbb, 0x86, 0x0d, 0xa3, 0x92, 0x04, 0x2b, 0xe3, 0xa2, 0xa0, 0x65, 0x08, 0xf2, 0x3d,
	0xb8, 0x8b, 0x45, 0xaa, 0x8b, 0xb3, 0x2c, 0x8d, 0xc2, 0x96, 0xf2, 0xf8, 0x75, 0xca, 0x0f, 0xa0,
	0xdf, 0xcc, 0x70, 0x96, 0x6b, 0xb7, 0xc0, 0x34, 0xda, 0xf2, 0x2c, 0x34, 0xa5, 0x37, 0xbe, 0xc2,
	0x27, 0xb0, 0xd5, 0x0c, 0x18, 0x6d, 0x8f, 0xd9, 0xa4, 0x3f, 0x1d, 0x8a, 0x76, 0x06, 0xa1, 0x6c,
	0x26, 0x1a, 0x73, 0xc7, 0x98, 0xd6, 0x33, 0xdf, 0x11, 0x7f, 0x63, 0xc0, 0xbb, 0x7e, 0x4b, 0x8b,
	0xa6, 0xd4, 0x9c, 0xd3, 0x05, 0x8d, 0xdb, 0x41, 0xdb, 0xca, 0x9f, 0x43, 0x6f, 0xa1, 0x55, 0xaa,
	0x8b, 0x28, 0x18, 0x87, 0x93, 0xfe, 0xf4, 0x50, 0x58, 0x55, 0x8b, 0x9b, 0x62, 0x71, 0xea, 0xbb,
	0x5e, 0x19, 0x57, 0xd4, 0x33, 0x92, 0x8c, 0x9e, 0x41, 0xbf, 0x53, 0xe6, 0xf7, 0x20, 0xfc, 0xa8,
	0x6b, 0x0a, 0xa3, 0x39, 0xf2, 0x21, 0x6c, 0x5f, 0xaa, 0x65, 0xa5, 0x29, 0x86, 0x16, 0x1c, 0x05,
	0x4f, 0xd9, 0xf4, 0x6b, 0x08, 0xbd, 0xf6, 0x05, 0xfe, 0x39, 0x00, 0x78, 0x87, 0xa5, 0x23, 0xb8,
	0x7b, 0xc3, 0x81, 0x8f, 0x7b, 0xb4, 0x71, 0xe0, 0xf8, 0x27, 0xbb, 0xfa, 0xf5, 0xfb, 0x4b, 0xf0,
	0x83, 0xc5, 0x2f, 0xe4, 0xe5, 0x23, 0xd9, 0x7e, 0x23, 0x92, 0x16, 0x21, 0x57, 0x74, 0x58, 0x4b,
	0x5a, 0x80, 0x5c, 0xd1, 0x61, 0x2d, 0x7d, 0xee, 0x72, 0x75, 0xbd, 0x8e, 0xf5, 0x91, 0x0f, 0xe4,
	0xfd, 0xc3, 0x78, 0xff, 0x6f, 0x17, 0x51, 0xd7, 0x93, 0x58, 0xfc, 0xdb, 0x73, 0xa4, 0x3b, 0x8c,
	0x1f, 0x74, 0x74, 0x9b, 0x2d, 0xf0, 0x2b, 0x06, 0x3b, 0x27, 0xfa, 0xff, 0xf2, 0x38, 0xf1, 0x71,
	0xbc, 0xe4, 0xb7, 0x4d, 0xe3, 0x78, 0x17, 0x86, 0xb6, 0x9a, 0x0b, 0xfb, 0x01, 0x13, 0x6f, 0x80,
	0xb4, 0xf3, 0x9e, 0xff, 0x25, 0x1e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x7d, 0xb3, 0x32,
	0x8f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotifyClient is the client API for Notify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotifyClient interface {
	PostNotify(ctx context.Context, in *HttpNotifyRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
	GetNotify(ctx context.Context, in *HttpNotifyRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
}

type notifyClient struct {
	cc *grpc.ClientConn
}

func NewNotifyClient(cc *grpc.ClientConn) NotifyClient {
	return &notifyClient{cc}
}

func (c *notifyClient) PostNotify(ctx context.Context, in *HttpNotifyRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, "/pay.Notify/PostNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyClient) GetNotify(ctx context.Context, in *HttpNotifyRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, "/pay.Notify/GetNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServer is the server API for Notify service.
type NotifyServer interface {
	PostNotify(context.Context, *HttpNotifyRequest) (*httpbody.HttpBody, error)
	GetNotify(context.Context, *HttpNotifyRequest) (*httpbody.HttpBody, error)
}

// UnimplementedNotifyServer can be embedded to have forward compatible implementations.
type UnimplementedNotifyServer struct {
}

func (*UnimplementedNotifyServer) PostNotify(ctx context.Context, req *HttpNotifyRequest) (*httpbody.HttpBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostNotify not implemented")
}
func (*UnimplementedNotifyServer) GetNotify(ctx context.Context, req *HttpNotifyRequest) (*httpbody.HttpBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotify not implemented")
}

func RegisterNotifyServer(s *grpc.Server, srv NotifyServer) {
	s.RegisterService(&_Notify_serviceDesc, srv)
}

func _Notify_PostNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).PostNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pay.Notify/PostNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).PostNotify(ctx, req.(*HttpNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notify_GetNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).GetNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pay.Notify/GetNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).GetNotify(ctx, req.(*HttpNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pay.Notify",
	HandlerType: (*NotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostNotify",
			Handler:    _Notify_PostNotify_Handler,
		},
		{
			MethodName: "GetNotify",
			Handler:    _Notify_GetNotify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify.proto",
}
