// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: notify.proto

package pay

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _notify_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on NotifyRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *NotifyRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Version

	// no validation rules for OutTradeNo

	// no validation rules for PayAmount

	// no validation rules for Currency

	// no validation rules for ReturnUrl

	// no validation rules for AppId

	// no validation rules for SignType

	// no validation rules for Sign

	// no validation rules for OrderTime

	// no validation rules for UserIp

	// no validation rules for UserId

	// no validation rules for PayerAccount

	// no validation rules for ProductId

	// no validation rules for ProductName

	// no validation rules for ProductDescribe

	// no validation rules for Charset

	// no validation rules for CallbackJson

	// no validation rules for ExtJson

	// no validation rules for ChannelId

	// no validation rules for Method

	// no validation rules for FactAmt

	// no validation rules for FareAmt

	return nil
}

// NotifyRequestValidationError is the validation error returned by
// NotifyRequest.Validate if the designated constraints aren't met.
type NotifyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NotifyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NotifyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NotifyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NotifyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NotifyRequestValidationError) ErrorName() string { return "NotifyRequestValidationError" }

// Error satisfies the builtin error interface
func (e NotifyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNotifyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NotifyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NotifyRequestValidationError{}

// Validate checks the field values on NotifyResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *NotifyResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Status

	return nil
}

// NotifyResponseValidationError is the validation error returned by
// NotifyResponse.Validate if the designated constraints aren't met.
type NotifyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NotifyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NotifyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NotifyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NotifyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NotifyResponseValidationError) ErrorName() string { return "NotifyResponseValidationError" }

// Error satisfies the builtin error interface
func (e NotifyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNotifyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NotifyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NotifyResponseValidationError{}
