// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pay_gateway.proto

package pay

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayRequest struct {
	Version string `protobuf:"bytes,100,opt,name=version,proto3" json:"version,omitempty"`
	// 业务订单号
	OutTradeNo string `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	// 支付金额（分）
	PayAmount uint32 `protobuf:"varint,3,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	// 币种
	Currency string `protobuf:"bytes,20,opt,name=currency,proto3" json:"currency,omitempty"`
	// 接收通知的地址，不能带参数（即：不能包含问号）
	NotifyUrl string `protobuf:"bytes,4,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	// 支付后跳转的前端地址
	ReturnUrl string `protobuf:"bytes,5,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	// 系统给商户分配的app_id
	AppId string `protobuf:"bytes,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// 加密方法，RSA和MD5，默认RSA
	SignType string `protobuf:"bytes,7,opt,name=sign_type,json=signType,proto3" json:"sign_type,omitempty"`
	// 签名
	Sign string `protobuf:"bytes,14,opt,name=sign,proto3" json:"sign,omitempty"`
	// 业务方下单时间，时间格式: 年年年年-月月-日日 时时:分分:秒秒，例如: 2006-01-02 15:04:05
	OrderTime string `protobuf:"bytes,8,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	// 发起支付的用户ip
	UserIp string `protobuf:"bytes,9,opt,name=user_ip,json=userIp,proto3" json:"user_ip,omitempty"`
	// 用户在业务系统的id
	UserId string `protobuf:"bytes,18,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 支付者账号，可选
	PayerAccount string `protobuf:"bytes,10,opt,name=payer_account,json=payerAccount,proto3" json:"payer_account,omitempty"`
	// 业务系统的产品id
	ProductId string `protobuf:"bytes,11,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// 商品名称
	ProductName string `protobuf:"bytes,12,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	// 商品描述
	ProductDescribe string `protobuf:"bytes,13,opt,name=product_describe,json=productDescribe,proto3" json:"product_describe,omitempty"`
	// 参数编码，只允许utf-8编码；签名时一定要使用该编码获取字节然后再进行签名
	Charset string `protobuf:"bytes,15,opt,name=charset,proto3" json:"charset,omitempty"`
	// 回调业务系统时需要带上的字符串
	CallbackJson string `protobuf:"bytes,16,opt,name=callback_json,json=callbackJson,proto3" json:"callback_json,omitempty"`
	// 扩展json
	ExtJson string `protobuf:"bytes,17,opt,name=ext_json,json=extJson,proto3" json:"ext_json,omitempty"`
	// 渠道id（非必须），如果未指定method，系统会根据method来找到可用的channel_id
	ChannelId string `protobuf:"bytes,19,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// 例如：二维码支付，银联支付等。
	Method               string   `protobuf:"bytes,98,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayRequest) Reset()         { *m = PayRequest{} }
func (m *PayRequest) String() string { return proto.CompactTextString(m) }
func (*PayRequest) ProtoMessage()    {}
func (*PayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15bb988e8569f4a8, []int{0}
}

func (m *PayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayRequest.Unmarshal(m, b)
}
func (m *PayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayRequest.Marshal(b, m, deterministic)
}
func (m *PayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayRequest.Merge(m, src)
}
func (m *PayRequest) XXX_Size() int {
	return xxx_messageInfo_PayRequest.Size(m)
}
func (m *PayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayRequest proto.InternalMessageInfo

func (m *PayRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PayRequest) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

func (m *PayRequest) GetPayAmount() uint32 {
	if m != nil {
		return m.PayAmount
	}
	return 0
}

func (m *PayRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PayRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *PayRequest) GetReturnUrl() string {
	if m != nil {
		return m.ReturnUrl
	}
	return ""
}

func (m *PayRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *PayRequest) GetSignType() string {
	if m != nil {
		return m.SignType
	}
	return ""
}

func (m *PayRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *PayRequest) GetOrderTime() string {
	if m != nil {
		return m.OrderTime
	}
	return ""
}

func (m *PayRequest) GetUserIp() string {
	if m != nil {
		return m.UserIp
	}
	return ""
}

func (m *PayRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PayRequest) GetPayerAccount() string {
	if m != nil {
		return m.PayerAccount
	}
	return ""
}

func (m *PayRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *PayRequest) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *PayRequest) GetProductDescribe() string {
	if m != nil {
		return m.ProductDescribe
	}
	return ""
}

func (m *PayRequest) GetCharset() string {
	if m != nil {
		return m.Charset
	}
	return ""
}

func (m *PayRequest) GetCallbackJson() string {
	if m != nil {
		return m.CallbackJson
	}
	return ""
}

func (m *PayRequest) GetExtJson() string {
	if m != nil {
		return m.ExtJson
	}
	return ""
}

func (m *PayRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *PayRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type PayResponse struct {
	Result               *ReturnResult     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	GatewayOrderId       string            `protobuf:"bytes,2,opt,name=gateway_order_id,json=gatewayOrderId,proto3" json:"gateway_order_id,omitempty"`
	Data                 map[string]string `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PayResponse) Reset()         { *m = PayResponse{} }
func (m *PayResponse) String() string { return proto.CompactTextString(m) }
func (*PayResponse) ProtoMessage()    {}
func (*PayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15bb988e8569f4a8, []int{1}
}

func (m *PayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayResponse.Unmarshal(m, b)
}
func (m *PayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayResponse.Marshal(b, m, deterministic)
}
func (m *PayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayResponse.Merge(m, src)
}
func (m *PayResponse) XXX_Size() int {
	return xxx_messageInfo_PayResponse.Size(m)
}
func (m *PayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayResponse proto.InternalMessageInfo

func (m *PayResponse) GetResult() *ReturnResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *PayResponse) GetGatewayOrderId() string {
	if m != nil {
		return m.GatewayOrderId
	}
	return ""
}

func (m *PayResponse) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PayRequest)(nil), "pay.PayRequest")
	proto.RegisterType((*PayResponse)(nil), "pay.PayResponse")
	proto.RegisterMapType((map[string]string)(nil), "pay.PayResponse.DataEntry")
}

func init() { proto.RegisterFile("pay_gateway.proto", fileDescriptor_15bb988e8569f4a8) }

var fileDescriptor_15bb988e8569f4a8 = []byte{
	// 807 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x54, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xc7, 0x71, 0xec, 0xc4, 0xcf, 0x4e, 0xe3, 0x0c, 0xa1, 0x9d, 0xba, 0x04, 0x07, 0x93, 0x83,
	0x4b, 0x64, 0x6f, 0x6a, 0x50, 0x69, 0x23, 0x71, 0x48, 0xd4, 0x0a, 0x99, 0x43, 0x41, 0x4b, 0x7a,
	0xa1, 0x6e, 0x56, 0xcf, 0xbb, 0x53, 0x67, 0x9b, 0xdd, 0x99, 0x61, 0x76, 0x36, 0xe9, 0x12, 0x45,
	0x42, 0x7c, 0x01, 0x0e, 0xf0, 0xad, 0x38, 0x72, 0x45, 0xb2, 0x64, 0x71, 0xe3, 0x4b, 0xa0, 0x99,
	0x59, 0xa7, 0x11, 0xb7, 0x79, 0xbf, 0xdf, 0xef, 0xcd, 0xfb, 0x33, 0xef, 0x0d, 0x6c, 0x49, 0x2c,
	0x82, 0x19, 0x6a, 0x76, 0x89, 0xc5, 0x50, 0x2a, 0xa1, 0x05, 0xa9, 0x4a, 0x2c, 0x3a, 0x1f, 0xcf,
	0x84, 0x98, 0x25, 0xcc, 0x43, 0x19, 0x7b, 0xc8, 0xb9, 0xd0, 0xa8, 0x63, 0xc1, 0x33, 0x27, 0xe9,
	0x74, 0x4b, 0xd6, 0x5a, 0xd3, 0xfc, 0x8d, 0xa7, 0xe3, 0x94, 0x65, 0x1a, 0x53, 0x59, 0x0a, 0x5a,
	0xa1, 0x48, 0x53, 0xc1, 0x4b, 0xeb, 0xf1, 0x2c, 0xd6, 0x67, 0xf9, 0x74, 0x18, 0x8a, 0xd4, 0x4b,
	0x2f, 0x63, 0x7d, 0x2e, 0x2e, 0xbd, 0x99, 0x18, 0x58, 0x72, 0x70, 0x81, 0x49, 0x1c, 0xa1, 0x16,
	0x2a, 0xf3, 0x6e, 0x8e, 0xce, 0xaf, 0xf7, 0x5b, 0x1d, 0xe0, 0x7b, 0x2c, 0x7c, 0xf6, 0x53, 0xce,
	0x32, 0x4d, 0x28, 0xac, 0x5d, 0x30, 0x95, 0xc5, 0x82, 0xd3, 0x68, 0xb7, 0xd2, 0x6f, 0xf8, 0x4b,
	0x93, 0x3c, 0x81, 0x96, 0xc8, 0x75, 0xa0, 0x15, 0x46, 0x2c, 0xe0, 0x82, 0x56, 0x0c, 0x7d, 0x7c,
	0x77, 0x31, 0xef, 0x12, 0x68, 0x9f, 0xbe, 0x3a, 0x1a, 0xfc, 0x88, 0x83, 0x9f, 0x0f, 0x06, 0x4f,
	0x83, 0xc1, 0xeb, 0xfd, 0x3d, 0x1f, 0x44, 0xae, 0x4f, 0x8c, 0xf4, 0x85, 0x20, 0xfb, 0x00, 0xa6,
	0x03, 0x98, 0x8a, 0x9c, 0x6b, 0x5a, 0xdd, 0xad, 0xf4, 0x37, 0x8e, 0x5b, 0x8b, 0x79, 0x77, 0xbd,
	0xfd, 0x01, 0xfd, 0xe5, 0x8f, 0x7f, 0xff, 0xae, 0xfa, 0x0d, 0x89, 0xc5, 0x91, 0xa5, 0x49, 0x07,
	0xd6, 0xc3, 0x5c, 0x29, 0xc6, 0xc3, 0x82, 0x6e, 0xdb, 0x0c, 0x6e, 0x6c, 0xb2, 0x03, 0xc0, 0x85,
	0x8e, 0xdf, 0x14, 0x41, 0xae, 0x12, 0xba, 0x6a, 0xd9, 0x86, 0x43, 0x5e, 0xaa, 0xc4, 0xd0, 0x8a,
	0xe9, 0x5c, 0x71, 0x4b, 0xd7, 0x1c, 0xed, 0x10, 0x43, 0xf7, 0xa0, 0x8e, 0x52, 0x06, 0x71, 0x44,
	0xeb, 0x36, 0xf5, 0xe6, 0x62, 0xde, 0x5d, 0x83, 0xda, 0xe9, 0xe4, 0x72, 0x7f, 0xcf, 0xaf, 0xa1,
	0x94, 0xe3, 0x88, 0x3c, 0x80, 0x46, 0x16, 0xcf, 0x78, 0xa0, 0x0b, 0xc9, 0xe8, 0x9a, 0x0b, 0x6f,
	0x80, 0x93, 0x42, 0x32, 0xf2, 0x08, 0x56, 0xcd, 0x99, 0xde, 0xb1, 0xee, 0x3b, 0x8b, 0x79, 0xf7,
	0x3e, 0xdc, 0xbb, 0x55, 0xf9, 0xbe, 0xf7, 0xf5, 0x24, 0x9b, 0xf0, 0x89, 0x32, 0x0d, 0xb0, 0x52,
	0xf2, 0x12, 0x40, 0xa8, 0x88, 0xa9, 0xc0, 0x3c, 0x1e, 0x5d, 0xb7, 0x8e, 0x8f, 0x17, 0xf3, 0xee,
	0x08, 0x0e, 0x4e, 0x5f, 0x1d, 0x0c, 0x9e, 0xbe, 0xbe, 0xfa, 0xf2, 0xba, 0x3f, 0x70, 0xa7, 0xd1,
	0xf5, 0xc3, 0xab, 0xd1, 0xf5, 0x24, 0x5b, 0x5a, 0xfd, 0xc3, 0xdb, 0xf8, 0x9e, 0xdf, 0xb0, 0x37,
	0x9d, 0xc4, 0x29, 0x23, 0xf7, 0x60, 0x2d, 0xcf, 0x98, 0x0a, 0x62, 0x49, 0x1b, 0x36, 0xc9, 0xba,
	0x31, 0xc7, 0xf2, 0x3d, 0x11, 0x51, 0x72, 0x8b, 0x88, 0xc8, 0x67, 0xb0, 0x21, 0xb1, 0x60, 0x2a,
	0xc0, 0x30, 0xb4, 0xcf, 0x00, 0x96, 0x6e, 0x59, 0xf0, 0xc8, 0x61, 0xa6, 0x81, 0x52, 0x89, 0x28,
	0x0f, 0xb5, 0xb9, 0xa0, 0xe9, 0x1a, 0x58, 0x22, 0xe3, 0x88, 0x7c, 0x0a, 0xad, 0x25, 0xcd, 0x31,
	0x65, 0xb4, 0x65, 0x05, 0xcd, 0x12, 0x7b, 0x81, 0x29, 0x23, 0x0f, 0xa1, 0xbd, 0x94, 0x44, 0x2c,
	0x0b, 0x55, 0x3c, 0x65, 0x74, 0xc3, 0xca, 0x36, 0x4b, 0xfc, 0x59, 0x09, 0x9b, 0x49, 0x0b, 0xcf,
	0x50, 0x65, 0x4c, 0xd3, 0x4d, 0x37, 0x69, 0xa5, 0x69, 0x72, 0x0d, 0x31, 0x49, 0xa6, 0x18, 0x9e,
	0x07, 0x6f, 0x33, 0xc1, 0x69, 0xdb, 0xe5, 0xba, 0x04, 0xbf, 0xcd, 0x04, 0x27, 0xf7, 0x61, 0x9d,
	0xbd, 0xd3, 0x8e, 0xdf, 0x72, 0xfe, 0xec, 0x9d, 0xb6, 0xd4, 0x0e, 0x40, 0x78, 0x86, 0x9c, 0xb3,
	0xc4, 0x94, 0xf1, 0xa1, 0x2b, 0xa3, 0x44, 0xc6, 0x11, 0xf9, 0x04, 0xea, 0x29, 0xd3, 0x67, 0x22,
	0xa2, 0x53, 0xfb, 0x1e, 0xf5, 0xc5, 0xbc, 0xbb, 0xb2, 0x5b, 0xf1, 0x4b, 0xb4, 0xf7, 0x67, 0x05,
	0x9a, 0x76, 0x23, 0x32, 0x29, 0x78, 0x66, 0x6a, 0xaa, 0x2b, 0x96, 0xe5, 0x89, 0xb6, 0x23, 0xdf,
	0x1c, 0x6d, 0x0d, 0x25, 0x16, 0x43, 0xdf, 0xce, 0x95, 0x6f, 0x09, 0xbf, 0x14, 0x90, 0x3e, 0xb4,
	0xcb, 0x3d, 0x0f, 0xdc, 0xb3, 0xc7, 0x11, 0x5d, 0xb1, 0xf1, 0xef, 0x94, 0xf8, 0x77, 0x06, 0x1e,
	0x47, 0x64, 0x08, 0xab, 0x11, 0x6a, 0xa4, 0xb5, 0xdd, 0x6a, 0xbf, 0x39, 0xea, 0xd8, 0x2b, 0x6f,
	0x05, 0x1d, 0x3e, 0x43, 0x8d, 0xcf, 0xb9, 0x56, 0x85, 0x6f, 0x75, 0x9d, 0xaf, 0xa0, 0x71, 0x03,
	0x91, 0x36, 0x54, 0xcf, 0x59, 0xe1, 0x36, 0xd0, 0x37, 0x47, 0xb2, 0x0d, 0xb5, 0x0b, 0x4c, 0x72,
	0x56, 0x46, 0x73, 0xc6, 0xe1, 0xca, 0x93, 0xca, 0xe8, 0x07, 0xbb, 0xde, 0xdf, 0xb8, 0xe8, 0xe4,
	0x39, 0x98, 0x9f, 0x87, 0x6c, 0xbe, 0x8f, 0x67, 0xd7, 0xbe, 0xd3, 0xfe, 0x7f, 0x02, 0xbd, 0x07,
	0xbf, 0xfe, 0xf5, 0xcf, 0xef, 0x2b, 0x1f, 0xf5, 0xda, 0xde, 0xc5, 0x23, 0x4f, 0x62, 0xe1, 0x5d,
	0xb9, 0xf6, 0x5c, 0x1f, 0x56, 0x3e, 0x3f, 0xbe, 0x0b, 0xdb, 0x32, 0x9f, 0x0e, 0xe5, 0x5b, 0x11,
	0x5a, 0xc7, 0xb2, 0xb8, 0x69, 0xdd, 0xfe, 0x29, 0x5f, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x48,
	0xd9, 0x61, 0x53, 0xf2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PayGatewayClient is the client API for PayGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayGatewayClient interface {
	Pay(ctx context.Context, in *PayRequest, opts ...grpc.CallOption) (*PayResponse, error)
}

type payGatewayClient struct {
	cc *grpc.ClientConn
}

func NewPayGatewayClient(cc *grpc.ClientConn) PayGatewayClient {
	return &payGatewayClient{cc}
}

func (c *payGatewayClient) Pay(ctx context.Context, in *PayRequest, opts ...grpc.CallOption) (*PayResponse, error) {
	out := new(PayResponse)
	err := c.cc.Invoke(ctx, "/pay.PayGateway/pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayGatewayServer is the server API for PayGateway service.
type PayGatewayServer interface {
	Pay(context.Context, *PayRequest) (*PayResponse, error)
}

// UnimplementedPayGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedPayGatewayServer struct {
}

func (*UnimplementedPayGatewayServer) Pay(ctx context.Context, req *PayRequest) (*PayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}

func RegisterPayGatewayServer(s *grpc.Server, srv PayGatewayServer) {
	s.RegisterService(&_PayGateway_serviceDesc, srv)
}

func _PayGateway_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayGatewayServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pay.PayGateway/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayGatewayServer).Pay(ctx, req.(*PayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PayGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pay.PayGateway",
	HandlerType: (*PayGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "pay",
			Handler:    _PayGateway_Pay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pay_gateway.proto",
}
